name: my-fastapi-app
provider: gcp
flavor: run-lite
version: 1

collections:
- name: dev
  region: us-east1
  base_domain: dev.mynextsite.com
  account_id: "theta-era-421317"
  environments:
  - name: staging
    environment_variables:
    - name: DATABASE_URL
      value: "value://from_db_provider"